sudo: false

language: node_js

node_js:
  - "stable"

services:
  - mongodb

cache:
  directories:
    - "node_modules"

script:
  - npm run test
  - npm run coveralls

notifications:
  email: false
