sudo: false

language: node_js

node_js:
  - stable

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  
script:
  - npm run test 
  - npm run coveralls

notifications:
  email: false
